### ISSUE TITLE
xcode9 has many warnings

### ISSUE THREAD

**Issue by neng18** [ReactiveCocoa/ReactiveObjC#120] opened 2017-09-25 02:33 UTC
example： ()  should be  Insert 'void'.

Please to fix.

**Comment by ikesyo** [comment] 2017-09-25 04:29
I can't see any warnings. What is the version you are using?

**Comment by neng18** [comment] 2017-09-25 04:33
xcode 9
![image](https://user-images.githubusercontent.com/6883455/30792553-c1b7b3d2-a1ed-11e7-8328-5c5b8fc871a6.png)

**Comment by faimin** [comment] 2017-09-25 04:34
it's same to [#115](https://github.com/ReactiveCocoa/ReactiveObjC/issues/115),

```gcc
#pragma clang diagnostic ignored "-Wstrict-prototypes"
```
will be help

**Comment by neng18** [comment] 2017-09-25 04:39
Thanks.

**Comment by ikesyo** [comment] 2017-09-25 04:48
I'm saying about ReactiveObjC's version, not Xcode version 😅

**Comment by ikesyo** [comment] 2017-09-25 04:57
Closing as a duplicate of #115.

**Closed by ikesyo** 2017-09-25 04:57 UTC
